stages:
  - trigger_jenkins

trigger_jenkins:
  stage: trigger_jenkins
  image: alpine:latest  # Lightweight image with apk package manager
  script:
    - apk add --no-cache curl  # Install curl
    - curl -X POST http://
  only:
    - main
    - dev
  tags:
    - jenkins
    - docker


